### ISSUE TITLE
Printing Leaflet map with popup to select different formats using MapFish

### ISSUE THREAD

**Issue by YBNayak** [aratcliffe/Leaflet.print#13]
Sir i am printing  leaflet map using mapFish,its working fine but i want  to give popup to choose different formats like A4,A3,and Legal.how to do? by clicking on printing icon i want to get popup. please help me out. Thank you

**Comment by aratcliffe** [comment]
The showLayouts print control option controls whether available print layouts are displayed when the control is clicked - it defaults to true. When true the control will show the names of any layouts the MapFish print service has been configured with.
