### ISSUE TITLE
printing clusters

### ISSUE THREAD

**Issue by vlasvlasvlas** [aratcliffe/Leaflet.print#14]
Hi! just wanna know, will this work if i print a map with clusters / clustering multiple points into zones / 1 point?

i mean this kind of maps
http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

thanks!

**Comment by aratcliffe** [comment]
If the clustering solution uses any of the supported layer types (see the readme) in theory it should. I've never tried myself though.

**Comment by jnordling** [comment]
Was there any update on this. Does not look like the cluster layer is one of the supported types.

**Comment by aratcliffe** [comment]
Hi Jon, support has only been implemented for the layer types we use or for those for which other contributors have provided implementations.
