### ISSUE TITLE
sample program not printing 

### ISSUE THREAD

**Issue by phonebooks** [aratcliffe/Leaflet.print#16]
Forgive me I am new to this system --

when I run the program below is gives me this error ... 
do I have to install map-fish print just to try this out ??
is there a different way ??

ReferenceError: printConfig is not defined

The code is below - any help would be truly appreciated !!

<!doctype html>
<html>
  <head>
    <title>Leaflet Printing</title>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.3/leaflet.css"/>
    <link rel="stylesheet" href="../dist/leaflet.print.css"/>
  </head>
  <body>
    <div id="map" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></div>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
    <script src="../dist/leaflet.print.js"></script>
    <script src="http://localhost:8080/mapfish-print/pdf/info.json?var=printConfig"></script>
     <script>
      var map,
            printProvider,
            printControl,
            ll = new L.LatLng(-36.852668, 174.762675);
        map = L.map('map', {
            center: ll,
            zoom: 15
        });
        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);
        L.marker(ll).addTo(map);
        // Create the print provider, subscribing to print events
        printProvider = L.print.provider({
          capabilities: printConfig,
          method: 'GET',
        dpi: 254,
        outputFormat: 'pdf',
        customParams: {
        mapTitle: 'Print Test',
        comment: 'Testing Leaflet printing'
        }
        });
        // Create a print control with the configured provider and add to the map
        printControl = L.control.print({
        provider: printProvider
        });
        map.addControl(printControl);
    </script>
  </body>
</html>

**Comment by aratcliffe** [comment]
Yes this requires an installation of mapfish.

**Comment by phonebooks** [comment]
Thank you -- is there a nice clear concise document for installing it ?? 
I am installing on OS X -- I tried the document at mapfish,com to install but I get  can not find symbol errors

**Comment by aratcliffe** [comment]
Hi, we install the mapfish print servlet under Tomcat. From memory you should be able to install by downloading the WAR file and deploying to your server's webapps directory. Take a look at the Java Servlet instructions on this page.
