### ISSUE TITLE
Plugin Chokes on large map scales

### ISSUE THREAD

**Issue by spydmobile** [aratcliffe/Leaflet.print#17]
If you add a map scale to the mapfish config.yaml such as 1:16,000,000 with the line (without quotes):
"  - 16000000 "
when geoserver returns capabilities in json it will report the large value in scientific notation
{"name":"1:16,000,000","value":"1.6E7"}
The print module, will choke on this value when it does _getScale and return 1 causing geoserver to fail.

a simple suggestion would be to wrap the scales[i].value in the function in Number() which would convert any scientific notation back to numeric for the calculation. 

If you modify the diff calculation and the scale calculation in the while loop and wrap the scale value in the number function, this will fix the issue.

**Comment by aratcliffe** [comment]
Thanks for the fix. I've updated the plugin now.
