### ISSUE TITLE
State of this Plugin?

### ISSUE THREAD

**Issue by astridx** [aratcliffe/Leaflet.print#28]
Today I installed this Plugin with the current Geoserver Print Module (v2.15) and Leaflet 0.7.
I could print my map.
After that I used Leafled 1.6.0. Now I get Errors on the Geoserver.

As I like to use the current Leaflet Versin I would like to know if someone else uses this Plugin with current Versions of GeoServer and Leaflet or if it is planed to update this plugin.

**Comment by aratcliffe** [comment]
Hi Astrid, I haven't tested this plugin with Leaflet 1.x but I'd recommend using a client-side, canvas-based solution now that it's well supported in all modern browsers. You could try this plugin: https://github.com/rowanwins/leaflet-easyPrint

**Comment by astridx** [comment]
Hi Adam,
thank you very much for your feedback.
